# Generated by Django 3.2.13 on 2022-11-23 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Timeline',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('follower_id', models.IntegerField()),
                ('username', models.CharField(max_length=50)),
                ('profile_img', models.TextField()),
                ('what', models.CharField(max_length=50)),
                ('content', models.TextField()),
                ('params', models.IntegerField()),
                ('router', models.CharField(max_length=50)),
                ('is_checked', models.BooleanField()),
            ],
        ),
    ]
