# Generated by Django 3.2.13 on 2022-11-24 01:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_remove_user_profile_msg'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='profile_msg',
            field=models.TextField(blank=True, max_length=500),
        ),
    ]
